name: Github context

run-name: ${{github.actor}}

on: 
 push:
  branches:
   - main

jobs:
 Github_context:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Deploy only from master
     if: github.ref == 'ref/heads/main'
     run: echo 'Deploying to production from main branch....'
   
     
