name: First WorkFLow CI

on: 
  push:
   branches:
    - 'feature'
    - 'main'

jobs:
 build_java:
  runs-on: ubuntu-latest
  steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
       java-version: '17'
       distribution: 'microsoft'
    

 test:
   needs: build_java
   runs-on: windows-latest
   steps:
    - run: echo 'test'
