name: Build and Push

env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
on:
 push:
  branches:
   - 'main'

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Display
     run: echo '${{env.DOCKER_USERNAME}}'
