name: Build and Push

env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
 DOCKER_PASSWORD: ${{secrets.DOCKER_PSWD}}
on:
 push:
  branches:
   - 'main'

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Display
     run: |
      echo '${{env.DOCKER_USERNAME}}'
      echo '${{env.DOCKER_PASSWORD}}'
