name: myNode JS

on:
 workflow_dispatch

jobs:
 build-node: 
  runs-on: ubuntu-latest
  steps:
   - name: Setup Node.js environment
     uses: actions/setup-node@v3.9.1
     with:
      node-version: '21'
